server:
  port: 8787
spring:
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest

  mail:
    host: smtp.yandex.ru
    port: 587
    username: testskarlet@yandex.ru
    protocol: smtp
    password: wwwkrilzvuadjmbk
    properties:
      "mail.transport.protocol": smtp
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
  datasource:
    url: jdbc:postgresql://postgresql:5432/sample
    #    url: jdbc:mysql://localhost:3306/sample
    driverClassName: org.postgresql.Driver
    username: postgres
    password: qwerty
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
